version: '3.8'

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    restart: always
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

networks:
  inception: