#!/bin/bash

cat <<EOF > /etc/mysql/init.sql
CREATE DATABASE IF NOT EXISTS $WP_DATABASE_NAME;
CREATE USER IF NOT EXISTS '$WP_DATABASE_USER'@'%' IDENTIFIED BY '$WP_DATABASE_PASSWORD';
GRANT ALL PRIVILEGES ON $WP_DATABASE_NAME.* TO '$WP_DATABASE_USER'@'%';
CREATE USER IF NOT EXISTS '$WP_USR'@'%' IDENTIFIED BY '$WP_PWD';
GRANT SELECT, INSERT, UPDATE, DELETE ON $WP_DATABASE_NAME.* TO '$WP_USR'@'%';
FLUSH PRIVILEGES;
EOF

mysql_install_db
mysqld